# Site Settings
title:               Yakim shu
tagline:            Hi, 這是我擴充腦內海馬體的地方。
description:
baseurl:            "/blogger"
img_url:            "../images/"
url:                "http://yakim-shu.github.io/blogger"
github:
  # url:               "https://lenpaul.github.io/blog"
author:
  name:              "Yakim shu"
  email:             "toromilk80129@gmail.com"
  # twitter:           "paululele"
  # instagram:         "paululele"
  github:            "yakim-shu"
  facebook:          "yakimshu"
  linkedin:          "yakimshu"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]


# Serving
detach:  false
port:    4000
host:    127.0.0.1
show_dir_listing: false