# Site Settings
title:               Yakim shu
tagline:            Hi, 這是我擴充腦內海馬體的地方。
description:
<<<<<<< HEAD
baseurl:            ""
img_url:            "../images/"
url:                "http://yakim-shu.github.io"
github:
  # url:               "https://lenpaul.github.io/blog"
author:
  name:              "Yakim shu"
  email:             "toromilk80129@gmail.com"
  github:            "yakim-shu"
  facebook:          "yakimshu"
  linkedin:          "yakimshu"
=======
baseurl:            "/blog"
img_url:            "../images/"
url:                #"https://lenpaul.github.io"
github:
  # url:               "https://lenpaul.github.io/blog"
author:
  name:              "Paul Le"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "lenpaul"
  facebook:          "Le.Paul.94"
  linkedin:          "lenpaul"
>>>>>>> parent of b10b9f6... Merge branch 'gh-pages'
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
<<<<<<< HEAD
linenos:             true
permalink:           none
gems:                [jekyll-paginate]

comments :
  provider : disqus
  disqus :
    short_name : yakim-shu    # 將內容替換成剛剛在disqus上申請的site name
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
=======
permalink:           none
gems:                [jekyll-paginate]

>>>>>>> parent of b10b9f6... Merge branch 'gh-pages'

# Serving
detach:  false
port:    4000
host:    127.0.0.1
show_dir_listing: false