# Site Settings
title:               Yakim shu
tagline:            Hi, 這是我擴充腦內海馬體的地方。
description:
baseurl:            ""
img_url:            "../images/"
url:                "https://yakimhsu.com"
github:
author:
  name:              "Yakim shu"
  email:             "toromilk80129@gmail.com"
  github:            "yakim-shu"
  facebook:          "yakimshu"
  linkedin:          "yakimshu"
paginate:            10


# Build settings
markdown:            kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
highlighter:         rouge
linenos:             true
permalink:           none
plugins:                [jekyll-paginate]

# Gems
gems: [jekyll-paginate]

comments :
  provider : disqus
  disqus :
    short_name : yakim-shu    # 將內容替換成剛剛在disqus上申請的site name
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
